### ISSUE TITLE
Create shortlinks for differents sections of the documentation

### ISSUE THREAD

**Issue by molant** [webhintio/webhint.io#185]
These shortlinks will be used in the output of sonar's cli among other places.

* [ ] What is a connector, formatter, rule
* [ ] Link to each individual rule
* [ ] Link to each individual connector

Need to decide what shortlink service to use. @kborchers is there any preference in the JS Foundation?

**Comment by kborchers** [comment]
There is no specific preference on our side. My question though would be why do they need to be shortened?

**Comment by molant** [comment]
It makes it easier to update the target url if needed without having to change the code. Also short urls are could be easier to remember. I think it was bluebird who did something similar to point to common issues and/or documentation in the console.

**Comment by molant** [comment]
Also it makes it easier for analytics and track if people use them.

**Comment by kborchers** [comment]
All good reasons! 😺 

If the service chosen persists the links indefinitely, for free, run with it. If there is cost to ensure that the links are maintained indefinitely (or at least until that service dies 😉), please gather that info and email me to review before proceeding.

**Comment by molant** [comment]
I think that with all the changed done to the CLI in the last few months this is no longer needed so closing.
