### ISSUE TITLE
Clean up Button CSS Code

### ISSUE THREAD

**Issue by ststimac** [webhintio/webhint.io#196]
When I edited the CSS originally, I changed the background color of buttons to all be red, but there are some blue buttons as well and there's some overlap happening in places in different CSS files that can probably be condensed & cleaned up so more code is shared. 

I just need to do some CSS clean up.

**Comment by ststimac** [comment]
Making a note for myself that some of the styles I need to clean up here are dependent on the scanner & scan result CSS files.

**Comment by ststimac** [comment]
We have two CSS files called scan-results.css. One is under the CSS folder, and then we have css > scan > scan-results.css. They both share a good amount of code but not all of it is the same. 

Do we need both?

**Comment by sarvaje** [comment]
We need to find a way to share styles between the website and the html formatter. Until then, I'm afraid that we need both.

**Comment by ststimac** [comment]
@sarvaje ok. Does it matter where I put my code that I'm consolidating?

**Comment by sarvaje** [comment]
IIRC, you should make the changes in both if you want to have the changes available for the html formatter when the formatter is used apart from the website.

**Comment by sarvaje** [comment]
> And one more question (sorry). Which one is the HTML Formatter file?

No problem :)

The formatter is in the `hint` repository. The styles are here: https://github.com/webhintio/hint/tree/master/packages/formatter-html/src/assets/styles

The files has the same name as in the website, but they contain only the styles we use in the formatter. It would be great to have a place to share the styles/script to not have to make the changes twice :(

**Comment by ststimac** [comment]
Hmmm. Are those getting pulled into thwe webhint-theme folder under the webhint.io?
I'm confused because we have two CSS files for scan results with nearly the same code in the webhint.io repo.

**Comment by sarvaje** [comment]
Let me take a look, I don't remember exactly what happen with the styles in the website.

**Comment by sarvaje** [comment]
@ststimac I'm going to explain what are we doing, but if you have any question, let me know please.

The file that contains the styles for the scanner is (these styles are used only in the scanner): https://github.com/webhintio/hint/blob/master/packages/formatter-html/src/assets/styles/scan/scan-results.css and we are sharing that file between the CLI and the website.

When we build the website, we copy this file to the website so the results look the same in both, the website and the cli, so if you need to change something for the scanner, you must do the changes only in the formatter.

All the others CSS files in the formatter contains styles shared in the whole website (columns/buttons/sections/etc.) If you change any of these in the website, then you need to make the changes in the formatter too (if the formatter use it).

If you have any question, let me know!

**Comment by ststimac** [comment]
OK that makes sense, thank you!
