### ISSUE TITLE
Rewrite documentation.css site-intro CSS

### ISSUE THREAD

**Issue by ststimac** [webhintio/webhint.io#225]
If documentation.css gets loaded anywhere other than the documentation section, it will affect pages with subtitles. This the scanner page on the live site right now: 

<img width="1433" alt="screen shot 2017-10-04 at 3 49 13 pm" src="https://user-images.githubusercontent.com/18073131/31203360-a068c8ee-a91b-11e7-83e2-c54ebf4ad847.png">

Need to rewrite the site-intro CSS so that subtitles don't get bumped to display inline through flexbox. An easy fix for now would be to just make sure documentation.css doesn't get loaded outside of the Docs section but if we add subtitles at a later time, the CSS will need to be re-written anyway.

**Comment by molant** [comment]
Let's move the css elsewhere then and deal with that problem if/when we have it

**Comment by sarvaje** [comment]
That's weird, I removed that css file from the scanner :s

**Comment by ststimac** [comment]
@sarvaje I think you maybe did in the scanner + scan results PR because I don't see it in my scanner branch.

**Comment by sarvaje** [comment]
Yep, I did that change in the scanner + scan results PR, but that PR is using you branch `scanner`

**Comment by ststimac** [comment]
Yes, I wanted to make a note here because I'm seeing it on the live site at sonarwhal.com/scanner :]

**Comment by antross** [comment]
Need to verify if this is already fixed.

**Comment by ststimac** [comment]
This is fixed. If we add subtitles to the documentation pages, we'll have some HTML to restructure slightly but I don't think we'll be doing that.
