### ISSUE TITLE
Update changelog's design

### ISSUE THREAD

**Issue by alrra** [webhintio/webhint.io#392]
Now that the rules (and soon formatters and parses) are no longer included in `sonarwhal`, and each of them will have it's own changelog, we should start a discussion about what should be display on the https://sonarwhal.com/about/changelog/ page.

**Comment by alrra** [comment]
Note: GitHub provides a [feed for releases](https://github.com/sonarwhal/sonarwhal/releases.atom).

**Comment by molant** [comment]
We need to take into account that we point the user to that url when there's a new version:

![image](https://user-images.githubusercontent.com/606594/37436435-312aec1a-27a5-11e8-8cea-eb9af5f621d0.png)

**Comment by alrra** [comment]
Talking to @molant, we were thinking that maybe we should have some kind of aggregator of all the changelogs, similar to:

https://changelog.travis-ci.com/
https://blog.github.com/changelog/

**Comment by ststimac** [comment]
Those two are pretty different content & design-wise. The Travis one seems to just be summaries with links and the github one links out to individual update pages with summaries and links.

**Comment by molant** [comment]
The general idea is that instead of grouping by version we group by date and put all the updates of all the packages at that time.

Structure wise, something like the following:

![image](https://user-images.githubusercontent.com/606594/43927758-642c78c4-9be3-11e8-866b-b566184e0510.png)

**Comment by ststimac** [comment]
Got it. Ok.

**Comment by ststimac** [comment]
Are the changes for each package going to be grouped into bug fixes/improvements and new features still?

**Comment by molant** [comment]
The changelog comes with that information. I think it will be useful to have it but it could have a different visual. Up to you!

**Comment by ststimac** [comment]
Here are a couple different variations for an updated layout:

![changelog_08-2018-01](https://user-images.githubusercontent.com/18073131/44431170-e3591400-a551-11e8-9882-60a2e97acee2.png)
__

![changelog_08-2018_changelog-update-2](https://user-images.githubusercontent.com/18073131/44431175-e94ef500-a551-11e8-9e8c-22e679ce1f82.png)

--

![changelog_08-2018_changelog-update-3](https://user-images.githubusercontent.com/18073131/44431186-efdd6c80-a551-11e8-95b9-e85d871656c5.png)

--

![changelog_08-2018_changelog-update-4](https://user-images.githubusercontent.com/18073131/44431202-f9ff6b00-a551-11e8-9255-72612d49a127.png)

**Comment by molant** [comment]
I think I like the first option best. @webhintio/core what do you think?

**Comment by alrra** [comment]
No. 3 for me.

**Comment by antross** [comment]
I like the first one best, but all are good.

**Comment by ststimac** [comment]
I prefer option 2.

**Comment by sarvaje** [comment]
+1 to option 1

**Comment by molant** [comment]
| Option | Votes |
| --------|-------|
| 1 |  3 (@sarvaje, @antross, @molant) |
| 2 |  1 (@ststimac) |
| 3 |  1 (@alrra) |

Do we have a winner?

**Comment by molant** [comment]
@ststimac we've merged a big PR in the site that changes the templating system from handlebars to ejs. You might want to branch again from master if you've started working on this to avoid messy conflicts and headaches.

**Comment by ststimac** [comment]
Nope! Haven't started with the code yet so that's fine :)

**Comment by ststimac** [comment]
I'll go in and ensure the design & code is up to date, not sure what is needed on the backend.
