### ISSUE TITLE
Configure live site

### ISSUE THREAD

**Issue by molant** [webhintio/webhint.io#4]
Things to do:

* [X] Create Azure website
* [X] Update DNS domains
* [X] Set up lets encrypt
* [ ] Enforce https via `web.config`
* [ ] Find a way to not need `.html` for the urls via `web.config` probably
* [ ] Configure `brotli` and `zopfli` in `web.config` until we have a CDN and can deploy to it
* [ ] Redirect `www.sonarwhal.com` to  `sonarwhal.com` (DNS? `web.config`?)
* [ ] Make node listen to an specific path and update to the latest 7.x version
* [ ] Configure `HTST` and add domain to the [HSTS Preload List](https://hstspreload.org/)

**Comment by molant** [comment]
We already redirect to https

**Comment by alrra** [comment]
> We already redirect to https

@molant haha, I was just giving an example that not having the redirect is a common.
