### ISSUE TITLE
Add ability to link to a certain error

### ISSUE THREAD

**Issue by alrra** [webhintio/webhint.io#413]
When there are a lot of errors, I often find myself linking to the scan page, but also copy pasting the error, which is not ideal.

We should have a ![](https://user-images.githubusercontent.com/1223565/37779213-18a95104-2da9-11e8-9526-dbe8dacdc40d.png) for all of these:

![](https://user-images.githubusercontent.com/1223565/37779124-dc420a30-2da8-11e8-8954-709f432da3b9.png)

**Comment by molant** [comment]
Any proposal on how the link should look like?

**Comment by alrra** [comment]
> Any proposal on how the link should look like?

Maybe just add the link icon on hover?

![](https://user-images.githubusercontent.com/1223565/37784327-be91b9fc-2db4-11e8-9b79-4d236fcc348a.png)

(e.g.: see heading [here](https://remysharp.com/2018/02/01/how-to-cross-post-to-medium))

**Comment by molant** [comment]
Sorry, I meant the url of the link. I guess something like `#rule-name-error-number` would work

**Comment by alrra** [comment]
> #rule-name-error-number would work

`#<rule-name>-error-<number>` works for me!

**Comment by sarvaje** [comment]
closing in favor of https://github.com/webhintio/hint/issues/1429
