### ISSUE TITLE
`Other` rule category needs an icon

### ISSUE THREAD

**Issue by alrra** [webhintio/webhint.io#463]
Ref: https://sonarwhal.com/docs/user-guide/rules/

**Comment by ststimac** [comment]
What happened to the rule/hint categories page? The 'other' category is missing and now the different categories aren't in alphabetical order?

**Comment by molant** [comment]
We changed the only rule in the "other" category to another one. I don't thing the categories where ever in alphabetical order (or at least not on purpose).

**Comment by molant** [comment]
That said, we still need an "other" icon.

**Comment by ststimac** [comment]
We have one. @sarvaje has it.

**Comment by alrra** [comment]
From: https://github.com/webhintio/hint/blob/77462f93719f57d1662a3839b22a0fc6b263693a/packages/formatter-html/src/assets/images/scan/other-icon.svg

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 72 72"><style>.a{fill:#2d28a1}</style><path fill="#acadda" d="M51.1 10.2H3.4A3.4 3.4 0 0 0 0 13.6v44.8c0 1.9 1.5 3.4 3.4 3.4h47.8c1.9 0 3.4-1.5 3.4-3.4V13.7c-.1-1.9-1.6-3.5-3.5-3.5zM5 56.8V16.2h44.4v40.6H5z"/><circle cx="15.6" cy="36" r="3.8" class="a"/><circle cx="27.2" cy="36" r="3.8" class="a"/><circle cx="38.9" cy="36" r="3.8" class="a"/></svg>
```

**Comment by ststimac** [comment]
We will need to rename it to match the other icon names.
