### ISSUE TITLE
favicon isn't updated correctly when scan ends

### ISSUE THREAD

**Issue by molant** [webhintio/webhint.io#469]
We are updating the favicon file via JavaScript but we don't have the cache busted names so we are just using `images/favicon_XXX.ico` in [`scanner-submit`](https://github.com/webhintio/webhint.io/blob/7ab5019c190b07e6e6fab2fc956ae5f34b8d9c55/src/sonarwhal-theme/source/js/scanner-submit.js#L323)

I'm not sure how to fix this (maybe have the icons commented in the HTML and uncomment them?)

**Comment by GuillaumeRossolini** [comment]
The red bird does appear for a second, and then it disappears.

Example with Chrome Canary with /static/images/favicon_failed-13305bf6b9.ico:
https://webhint.io/scanner/e3e5cfb3-8b1c-4018-98db-4684e288d904

**Comment by molant** [comment]
I think we are still executing the JS of the scanner results even though the test is finished. 
IIRC https://github.com/webhintio/webhint.io/pull/474 should fix that particular issue where the icon changes even though the results are finished. @sarvaje is that true?

Re updating the icon while the tests are running I still need to figure out how to do that.

**Comment by molant** [comment]
@sarvaje is taking care of this with the new results page.

**Comment by molant** [comment]
@sarvaje is this fixed with the new results page?

**Comment by sarvaje** [comment]
@molant I need to take a look at this.

**Comment by sarvaje** [comment]
It was fix, but I have create a new PR to update the icon as soon as we get some result. https://github.com/webhintio/webhint.io/pull/542
