### ISSUE TITLE
Make it more obvious the project is open source and the code is available on GitHub

### ISSUE THREAD

**Issue by alrra** [webhintio/webhint.io#491]
We don't seem to be converting website visitors to GitHub repository visitors.

---

I think one of the first things we can look into is make the GitHub icons more obvious (right now there are small and kinda hidden).

**Comment by ststimac** [comment]
I think we could also modify the intro text a bit to say that webhint is an open-source linting tool and link out from there as well.

**Comment by Malvoz** [comment]
> I think one of the first things we can look into is make the GitHub icons more obvious

The icons at the top on the right-hand side computes to `15x15`px, could probably double their size?

IMO, a link to GitHub in the menu would be nice. Even if only at smaller breakpoints such as when the menu is collapsed on mobile devices:

![webhint](https://user-images.githubusercontent.com/26493779/47799648-fe52bc00-dd2a-11e8-98a7-596fff315415.png)

**Comment by molant** [comment]
Good ideas @Malvoz 
Do you want to implement them?
