### ISSUE TITLE
empty.webhint.io contains invalid HTML

### ISSUE THREAD

**Issue by Calinou** [webhintio/webhint.io#492]
This probably has no real consequences, but [empty.webhint.io](https://empty.webhint.io) contains invalid HTML since its first line is `<DOCTYPE html>` instead of `<!DOCTYPE html>`.

For reference, this is the page's HTML source:

```html
<DOCTYPE html>
    <html>

    <head>
    </head>

    <body>
    </body>

    </html>
```

**Comment by alrra** [comment]
@Calinou Good catch, and thanks for opening this issue!

---

@sarvaje, @molant We should change the page to:

```
<!doctype html>
<title>empty</title>
```

**Comment by molant** [comment]
Fixed!
