### ISSUE TITLE
Deploy gets triggered (and fails) on PRs

### ISSUE THREAD

**Issue by molant** [webhintio/webhint.io#493]
Check the log of any recent PR, it will try to log into Azure. Need to find a way to prevent this.

**Comment by alrra** [comment]
>  Need to find a way to prevent this.

You can use the [`TRAVIS_PULL_REQUEST` environment variable](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions), or [Travis Ci conditions](https://docs.travis-ci.com/user/conditions-v1).
