### ISSUE TITLE
[hint] Additional HTTP headers

### ISSUE THREAD

**Issue by Malvoz** [webhintio/webhint.io#510]
- [`Cross-Origin-Resource-Policy`](https://fetch.spec.whatwg.org/#cross-origin-resource-policy-header) - enables authors to prevent other domains from loading resources by restricting any kind of cross-origin load to protect themselves against Spectre attacks. This header was originally named `From-Origin`.  [Available in Safari 12](https://webkit.org/blog/8332/release-notes-for-safari-technology-preview-59/).
- [`Cross-Origin-Window-Policy`](https://github.com/whatwg/html/issues/3740) - prevents third-parties from opening/controlling a window (relates to the `rel="noopener"` check, I think). In [Safari 12](https://webkit.org/blog/8332/release-notes-for-safari-technology-preview-59/) this was implemented and renamed from `Cross-Origin-Options`.
- [`Expect-CT`](https://tools.ietf.org/html/draft-ietf-httpbis-expect-ct-02)
- [`Feature-Policy`](https://wicg.github.io/feature-policy/)

Non-standard:
- [`X-Download-Options`](https://blogs.msdn.microsoft.com/ie/2008/07/02/ie8-security-part-v-comprehensive-protection/) for IE 8, [support suggested for MS Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18488178/).
- [`X-Permitted-Cross-Domain-Policies`](https://www.adobe.com/devnet-docs/acrobatetk/tools/AppSec/xdomain.html), considered a top-10 security header at [OWASP](https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#xpcdp).

If you want these as seperate issues at [webhintio/rfcs](https://github.com/webhintio/rfcs/issues) just let me know and I'll get to it.

**Comment by molant** [comment]
@Malvoz can you please open a single issue in RFCs called "Security headers" with all of these?
We can then decide if it makes sense to split them or just have one rule that checks for all of these.

We were also thinking about [CORB](https://github.com/webhintio/hint/issues/767)

Thanks!

**Comment by Malvoz** [comment]
Closing this per https://github.com/webhintio/rfcs/issues/38.
