### ISSUE TITLE
Site search not working

### ISSUE THREAD

**Issue by Malvoz** [webhintio/webhint.io#515]
[Currently](https://webhint.io/search/?q=searchterm), OpenSearch-searches return a status 500 response code.

Also, as a side note; the [opensearch spec says](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md#mime-type-applicationopensearchdescriptionxml) to serve the file with
`Content-Type: application/opensearchdescription+xml`.
However this _may_ change in the future as there's been a suggestion (https://github.com/dewitt/opensearch/pull/1) to change the content-type to `application/x-suggestions+json` instead.

**Comment by Malvoz** [comment]
@molant 
Unfortunately the issue persist.

**Comment by alrra** [comment]
> Unfortunately the issue persist.

Confirmed.

**Comment by Malvoz** [comment]
I don't want to open a new issue for this, @molant; **search queries that have no results** returns a 500 response code aswell. Try https://webhint.io/search/?q=noresultsforthisquery

**Comment by molant** [comment]
Thanks @Malvoz
