### ISSUE TITLE
Use illustrations from `artwork` repository

### ISSUE THREAD

**Issue by alrra** [webhintio/webhint.io#518]
Let's not duplicate things and use the illustrations from https://github.com/webhintio/artwork (published as [`@hint/artwork`](https://www.npmjs.com/package/@hint/artwork) on `npm`).

**Comment by RoryDuncan** [comment]
I can take a look at this one. 😃

**Comment by molant** [comment]
Perfect!
There are different ways of doing this. I was thinking of a post install task that copies the files in the right place but if you have a different idea let us know.
The current illustrations are under the webhint- theme folder.

Let us know if you run into any issue or have any question and thanks!

P

**Comment by RoryDuncan** [comment]
Yeah, I was thinking the same thing—based off my little bit of perusing.
I will certainly reach out if needed!
