### ISSUE TITLE
the scan will not perform 

### ISSUE THREAD

**Issue by luntrus** [webhintio/webhint.io#522]
Trying to use the website scanner I got an error message: 
Scan failed to start [code] <script src="https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js" integrity="sha384-bpcisN7hXHzDmg5JLgtPet7fpev9Wwwqgw8zlXpOh7AkvJ+wYjwrMzHH8fVvq1Dq" crossorigin="anonymous"></script>[/code]
[quote]
Probable issue: content-tss.js loaded:  https://webhint.io/scanner/
VM47:5 hosted page injected
content-ads.js:2 content-ads.js loaded:  https://webhint.io/scanner/
docsearch.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
www.google-analytics.com/analytics.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(index):1 Uncaught ReferenceError: docsearch is not defined
    at (index):1
    at (index):1 [/quote]

Awaiting analysis? 

luntrus

**Comment by molant** [comment]
Hi @luntrus,
it looks like the certificate hasn't been auto-renewed. We are currently working on it.

Thanks!

**Comment by molant** [comment]
This should be working now.
