### ISSUE TITLE
Allow to filter out third-party resource errors

### ISSUE THREAD

**Issue by Malvoz** [webhintio/webhint.io#536]
Naturally, most actionable improvements for developers will be that of 1st party content. I suggest in the future there could be a toggle to filter out errors applying to the content of third-party resources. 

For example, if I load a static `<script>` cross-origin without SRI, I'd still like to know that I should include the `integrity` attribute, however I may potentially want to filter out the error saying that the script should be served with a long `max-age` and the `immutable` `cache-control`-directives as I have no control over the script. (I could however raise the issue with the third-party content provider, which is why I think the default behavior should be for the scanner to display errors from all parties.)

**Comment by molant** [comment]
I consider this part of #233 so closing it.

We are exploring how to integrate webhint into an extension and part of the exercise is how to allow the users to easily configure it. Hopefully that solution will port over to the website but I don't know when that will happen. We are pretty busy with other things but if someone from outside the core team wants to tackle this we will make sure to help along the way.

Also, let me know if you want us to ping you once we have something ready design wise so you can share your feedback.

Thanks!

**Comment by Malvoz** [comment]
@molant ya just let me know, I'll gladly to provide feedback anywhere I can.
