### ISSUE TITLE
Missing Service Worker sonarwhal-worker.js causes broken docs

### ISSUE THREAD

**Issue by digitarald** [webhintio/webhint.io#544]
STR:
- Have the old service worker `sonarwhal-worker.js` installed
- Open https://webhint.io/docs/user-guide/ (Firefox Nightly)

Install code does a broken page:

![image](https://user-images.githubusercontent.com/8599/47190027-678b0600-d30d-11e8-9e97-5adcad445b6e.png)

The source really has no install code in the HTML:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/8599/47190130-d7998c00-d30d-11e8-9b68-f35d9845c4f0.png">

Logs:

> None of the “sha384” hashes in the integrity attribute match the content of the subresource.
user-guide
> None of the “sha384” hashes in the integrity attribute match the content of the subresource. user-guide
> Failed to register/update a ServiceWorker for scope ‘https://webhint.io/’: Load failed with status 404 for script ‘https://webhint.io/sonarwhal-worker.js’.

Hard refresh to circumvent the Service Worker, using Cmd-R, shows the correct page:

![image](https://user-images.githubusercontent.com/8599/47189991-34487700-d30d-11e8-87a2-711c0ee43e98.png)

Soft refresh returns the broken page again.

**Comment by molant** [comment]
🤦‍♂️

If we add a `sonarwhal-worker.js` that unregisters the service worker will it fix it?

**Comment by alrra** [comment]
Note: The [`Clear-Site-Data`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data) header is now supported in some browsers including Firefox.

**Comment by digitarald** [comment]
> Note: The Clear-Site-Data header is now supported in some browsers including Firefox.

Probably the best way to get rid of the stale worker.

**Comment by Malvoz** [comment]
As a quick fix, I'm pretty sure serving an empty `sonarwhal-worker.js` could fix this. The SW will be updated (and do nothing, which is currently the intention) for users that have the old worker cached.

**Comment by molant** [comment]
Thanks everyone

We want to add back again a service worker so I think we should be sending `Clear-Site-Data: "*"` when a user access sonarwhal.com to avoid having to send multiple service worker files (even if empty) or use one with a name that's not meaningful anymore.
I'm going to try to see if I can send it conditionally in IIS but if not we might have to create a new website for sonarwhal and update DNS to it.

**Comment by molant** [comment]
@digitarald there's now a PR for this. Don't know if you still have the old service worker activated somehow but it will nice to verify this works. Basically I'm adding the `Clear-Site-Data` header for all requests that arrive to our server to the host sonarwhal.com and send it with the redirect to webhint.io.

This is the network trace:

![image](https://user-images.githubusercontent.com/606594/47938955-e0a86280-dea2-11e8-9150-db433e30b2c5.png)
