### ISSUE TITLE
URLs are cached in Google Search

### ISSUE THREAD

**Issue by sarvaje** [webhintio/webhint.io#551]
There is people that found a link to the documentation in webhint, but those links are old and it looks like the are cached in google.
e.g. 
https://webhint.io/docs/user-guide/further-configuration/website-authentication/#page-heading
https://webhint.io/docs/contributor-guide/connectors/

We need to find out if there is a way to notify these changes to the search engines to update the cache.

**Comment by molant** [comment]
> In the meantime I think we can look at: https://www.google.com/webmasters/?

That's the idea. We already have an account and also in Bing. We have to investigate if we can trigger a new scan, update sitemap, etc. each time there's a deployment and there's none pending.


________________________________
