### ISSUE TITLE
Not able to install webhint cli

### ISSUE THREAD

**Issue by gakhrejah** [webhintio/webhint.io#552]
Hi Team,

We are trying to use webhint cli in a docker container . But after scanning a url ( hint <some url>) , we are getting the below error. The error says configuration file in invalid 

ERROR LOG

added 186 packages from 163 contributors in 19.077s
Error: Connector "jsdom" not found
    at new Engine (/usr/lib/node_modules/hint/dist/src/lib/engine.js:30:19)
    at exports.default (/usr/lib/node_modules/hint/dist/src/lib/cli/analyze.js:223:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    
We are using below node version
Node version : v10.12.0 

Steps followed to install the webhint cli
1) npm install -g --engine-strict hint
2) npm create hintrc -> we have use the default .hintrc file 
3) hint www.google.com -> after running this we are getting error

Please let us know what steps we should take to install the webhint cli and get a report generated .

**Comment by molant** [comment]
Hi @gakhrejah,

If you are going to use the default configuration you don't need to run `npm create hintrc`, webhint will use the built-in default one.

Couple things:
* Are you running node x86 or x64?
* Can you please run `hint https://www.google.com --debug` and paste the output in a comment?

Thanks!

**Comment by molant** [comment]
@gakhrejah I've created this issue in the right repo. Do you mind continuing the conversation there?

https://github.com/webhintio/hint/issues/1460

Thanks!
