### ISSUE TITLE
Search bar layout broken on smaller viewports 

### ISSUE THREAD

**Issue by ststimac** [webhintio/webhint.io#566]
<img width="867" alt="screen shot 2018-11-09 at 9 17 37 am" src="https://user-images.githubusercontent.com/18073131/48277770-79d5fc80-e400-11e8-8435-0b01eb1217ba.png">

I'm assuming this is due to the update to the menu that was just pushed live. It's not completely broken as when the viewport gets smaller it readjusts to the correct positioning. But there's a small window where it's broken.

**Comment by ststimac** [comment]
FYI @molant 

If I have time this afternoon, I'll look into it. I can't remember where exactly in the code this is.

**Comment by molant** [comment]
navigation.css I believe is the right place.

https://github.com/webhintio/webhint.io/commit/49d466ab041ef73c7b13e8ff88be991ee637364f

**Comment by molant** [comment]
I'll be taking care of this
