### ISSUE TITLE
Publish documentation for non-hint packages

### ISSUE THREAD

**Issue by molant** [webhintio/webhint.io#570]
Right now the only documentation we are publishing are the one under `hint/docs` and `hint-XXX`.
We are missing all the `connector`s, `parser`s, `formatter`s  and extensions (VS Code for now but soon browsers).

They should be part of the `user guide` and be processed at the same time as the hints and appear in the navigation menu:

![image.png](https://images.zenhubusercontent.com/56d5e96d6caf56c9d38d18fe/9d8cdbfe-7717-4346-b9fe-60a37bebf09d)

Ideally there should be a landing page for each category with an auto generated list (we used to have that for hints back in the day).

@sarvaje can you please estimate and start working on this?

**Comment by molant** [comment]
Didn't we auto update that file?
Maybe a manual one is OK for now. We don't have that many resources that aren't hints.


________________________________

**Comment by sarvaje** [comment]
Yes, the one I pointed you is an old one, but it is still in the repository
