### ISSUE TITLE
failing CI

### ISSUE THREAD

**Issue by DanielRuf** [webhintio/webhint.io#589]
https://travis-ci.org/webhintio/webhint.io/builds/472178714#L1631

**Comment by molant** [comment]
Thanks @DanielRuf !

Looks like the method to install the Azure CLI got changed. I've pushed a fix and I'll close this issue once I see the build passing.

**Comment by molant** [comment]
[Build is green again](https://travis-ci.org/webhintio/webhint.io/builds/476801831)
