### ISSUE TITLE
[docs] Issue with 'Formatters'

### ISSUE THREAD

**Issue by renestalder** [webhintio/webhint.io#631]
The formatters page seems missing or at least empty to me. Can somebody confirm that?

https://webhint.io/docs/user-guide/formatters/index.html

**Comment by renestalder** [comment]
@sarvaje Thanks for the fast reaction. That's awesome.

> I'm going to move this issue to https://github.com/webhintio/webhint.io

Just curious. The "Signal Issue" button on the website creates issues on the hint repository. That's how I created the issue.

Should that button not always create an issue on the webhint.io repository then?

**Comment by sarvaje** [comment]
@renestalder not always. Maybe it is a little confusing, but the thing is that the documentation itself is in the `hint` repository, so any issue related to the content of the documentation should be filled there. Then, when we build the website, we take the documentation from the `hint` repository and we copy/transform it to get what we need for the website. Some issues are related with that process and those should go to the `webhint.io` repository :)

But don't worry, some times with the documentation is not easy to know where the error comes from until we reproduce it :)

**Comment by molant** [comment]
@renestalder we've decided to semi-centralize everything into the `hint` repo and created issue templates there to make it easier for the community to file things. If we need to reroute the problem we will do it, now that GitHub has a built-in feature is not a problem at all 😊'

Thanks for your contributions!
