### ISSUE TITLE
Assess use of all capitalized lettering due to localization issues

### ISSUE THREAD

**Issue by ststimac** [webhintio/webhint.io#657]
Text that is all uppercase poses an issue for localization. I'd like to go through and assess everywhere we're using uppercase lettering and make updates with sentence casing. 

Right now we're using all caps in the following locations: 

- Top level nav
- Buttons
- Home page subheadings under "why use webhint"
- Documentation: Table of contents (can address in the ToC restructure/redesign)
- Scan results category overview
- Footer menu
(There may be more locations but off the top of my head and a quick review of the site gave me this list) 

A few of these we'll want to modify the type weight to compensate for losing the blockiness off all caps and we can experiment in-browser to see how changing the type will affect layout.

**Comment by ststimac** [comment]
I might be getting ahead of myself here as we don't have plans to localize the site but if capitalization causes issues with localization and people who use translate the site with an extension, I'd like to remove that issue :)

**Comment by ststimac** [comment]
@antross I might want to break this out into two tasks. Buttons, home page subheadings and the scan results page need a little more thorough design thought before making changes so there's clear hierarchy. 

The nav, footer, table of contents can be adjusted easily.

**Comment by antross** [comment]
Sounds good to me - feel free to split it up!

**Comment by ststimac** [comment]
This issue's PR will only address:

- top level nav
- changelog date (Month is all caps)
- table of contents
- footer menu
