### ISSUE TITLE
Remove aria-hidden=true from main nav [0.1]

### ISSUE THREAD

**Issue by ststimac** [webhintio/webhint.io#664]
axe is returning the following hints when we run the staged version of the site against webhint: 

```
line 1  col 4374  Error  ARIA hidden element must not contain focusable elements  axe
line 1  col 4832  Error  ARIA hidden element must not contain focusable elements  axe
```

This applies to the main navigation. We have two menu items that are hiding their submenus: "documentation" and "about" via aria-hidden="true" and then when a user clicks on either of those buttons, the submenu is shown by changing the value to aria-hidden="false".

This is triggering the aXe hint because the submenu items are focusable. 

```
<ul role="group" id="submenu-docs" class="navbar__submenu" aria-hidden="true">
<li><a href="/docs/contributor-guide/">Contributor Guide</a></li>  
<li><a href="/docs/user-guide/hints/">Hints</a></li>  
<li><a href="/docs/user-guide/">User Guide</a></li>  
</ul>
```

We need to remove aria-hidden completely from both `ul` submenus and replace with `hidden`. When the user clicks on the main nav button or tabs into the nav via keyboard and hits enter on "documentation" or "about" we need to remove `hidden` so that the submenu will appear. 

@sarvaje I need your assistance with this as I believe this requires JavaScript.

**Comment by sarvaje** [comment]
@ststimac yep, it will require js. I can take care of the js part :)
