### ISSUE TITLE
Details/summary doesn't work on Chrome

### ISSUE THREAD

**Issue by molant** [webhintio/webhint.io#667]
It's expanded and clicking on it doesn't do anything.

You can check the behavior in https://webhint.io/docs/user-guide/hints/hint-http-cache/

![image](https://user-images.githubusercontent.com/606594/54389563-99568d80-465d-11e9-82d7-9c52ec0368e3.png)

@sarvaje, @ststimac can you please take a look?

**Comment by ststimac** [comment]
@molant it looks like information/content is just straight up missing for the configuration. There should be content when you check the code under the devtools but there is nothing to show: 

<img width="517" alt="Screen Shot 2019-03-14 at 1 34 55 PM" src="https://user-images.githubusercontent.com/18073131/54389901-737db880-465e-11e9-8331-409121ba525b.png">

**Comment by ststimac** [comment]
There would be a div or something else in between the <details> but it's not technically broken, there's just no content so nothing is appearing when you click on the triangle.

**Comment by molant** [comment]
@sarvaje can you take a look at the scripts for the documentation?

**Comment by antross** [comment]
Looks like this ties back to `hint-http-cache/README.md`. The markdown looks like:

```md
<details><summary>How to configure Apache</summary>

Enabling Apache to automatically add the `Cache-Control` header
(as well as the equivalent `Expires` header) can be done using the
[`ExpiresActive` directive][expiresactive].
```

By the time we hit the extra blank line we're done with the HTML portion so it gets closed off (since you can't inline additional markdown within an inline HTML block). Were we trying to do something in the scripts to allow this?

Per https://daringfireball.net/projects/markdown/syntax#html
> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style `*emphasis*` inside an HTML block.

**Comment by sarvaje** [comment]
Same problem here: https://webhint.io/docs/user-guide/hints/hint-http-compression/

I'm going to take a look

**Comment by sarvaje** [comment]
@antross that is not the problem, that has been working since day 1. I have created a test project, and the same markdown, generate the right html. I'm taking a look if I can find why it is not working on the web :(
