### ISSUE TITLE
Code formatting looks broken in some cases

### ISSUE THREAD

**Issue by molant** [webhintio/webhint.io#679]
![image](https://user-images.githubusercontent.com/606594/54849182-c4b22b80-4ca0-11e9-8f36-bdaae28c9b6c.png)

https://webhint.io/docs/contributor-guide/how-to/formatter/

@ststimac can you please take a look?

**Comment by ststimac** [comment]
@molant the class "title" is being applied there and `.title` is reserved for all titles across the site. This needs a new class.

**Comment by ststimac** [comment]
So something in the markdown generation for the docs needs to be changed.

**Comment by molant** [comment]
The code is generated automatically so I'm not sure we can change anything into the generated code :/

**Comment by ststimac** [comment]
We can't change the class being applied to that particular part of the docs?

**Comment by molant** [comment]
That code is generated automatically 🤔
@sarvaje we might have to go back to the previous markdown renderer or see if there's a parameter or something to change how the code is generated

**Comment by sarvaje** [comment]
@molant, I went back to the previous renderer and the problem is still there. Maybe the problem is in another package. I'm going to continue investigating this.
