### ISSUE TITLE
Update homepage to include VS Code and browser extensions

### ISSUE THREAD

**Issue by antross** [webhintio/webhint.io#765]
Copy updates are in #764

**Comment by ststimac** [comment]
We will probably want to see if we can commission the artist who revamped Nellie so everything is in the same style.

Also Nellie VS Code stickers would be GREAT for conferences.

**Comment by antross** [comment]
> Also Nellie VS Code stickers would be GREAT for conferences.

😍😍😍

**Comment by antross** [comment]
> We will probably want to see if we can commission the artist who revamped Nellie so everything is in the same style.

Makes sense. Just to have this written down, it looks like the artist was [Mike Bonales](http://www.mikebonales.com) according to our [artwork repo](https://github.com/webhintio/artwork).

**Comment by molant** [comment]
Let me know how many images we need and I can contact him for a quote.


________________________________

**Comment by molant** [comment]
Let's repurpose this issue for updating the home page in general.

@hxlnt has worked in the copy and while there might be some updates, the structure is done.

Check the content of #764 for the text.

**Comment by ststimac** [comment]
@antross @molant @sarvaje @hxlnt 

Still need the illustrations so there are some gaps. And I think we really ought to have a shorter heading up at the top and then the webhint paragraph below it to balance out the top a bit. The hero area feels a bit uninteresting to me right now and almost a bit intimidating without that shorter heading to precede the block of text. Thoughts?

![home_update_092019-04](https://user-images.githubusercontent.com/18073131/65360762-ff484280-dbb5-11e9-822d-2da79d2b6835.png)

**Comment by ststimac** [comment]
Re-adjusted hero area
![home_update_092319](https://user-images.githubusercontent.com/18073131/65441896-0ce11080-dde0-11e9-93f4-264a10174bf6.png)

**Comment by molant** [comment]
LGTM, @hxlnt what do you think?
