### ISSUE TITLE
Re-work the main menu in the header

### ISSUE THREAD

**Issue by antross** [webhintio/webhint.io#766]
Need to account for adding extensions and how we want to direct users to each unique webhint endpoint depending on their needs.

**Comment by hxlnt** [comment]
This is blocked on https://github.com/webhintio/hint/issues/2780...

...also assigned to me. 🙃

**Comment by molant** [comment]
#2780 is done, think you can tackle this next sprint?

**Comment by hxlnt** [comment]
![image](https://user-images.githubusercontent.com/9647195/70668693-1cc30080-1c29-11ea-928c-e75362c545a9.png)

Thoughts? I think removing the GitHub link is OK since we have it linked at the right. (Edit: The About link should have the expandable triangle.)

**Comment by molant** [comment]
What does each item link to and what are the subitems? Some are obvious, but others might have several candidates.

Any reason why you picked this order? Not that I disagree, but I'd like to know the reasons 😊

Nit: "About" is expandable

**Comment by hxlnt** [comment]
Yup--this was my thought. Also, maybe Extensions should come before CLI.

1. Online scanner (keep as is)
2. Extensions
  - [VS Code extension](https://webhint.io/docs/user-guide/extensions/vscode-webhint/)
  - [Browser extension](https://webhint.io/docs/user-guide/extensions/extension-browser/)
2. CLI (keep as is)
3. Documentation (keep as is)
4. About (keep as is)

**Comment by molant** [comment]
> maybe Extensions should come before CLI

👍

I might switch browser and vs code, but at this point the best will be to do some A/B testing to see which one works best.

**Comment by antross** [comment]
This was completed by #890. Closing.
