### ISSUE TITLE
Add extensions link back to User Guide

### ISSUE THREAD

**Issue by hxlnt** [webhintio/webhint.io#796]
After https://github.com/webhintio/hint/pull/2837 was merged, the link to browser extensions disappeared from the User Guide sidebar. Guessing something with how the the static-site generator creates the sidebar needs to be adjusted.

**Comment by antross** [comment]
Actually https://github.com/webhintio/webhint.io/pull/793 is probably the culprit here. We have to publish the extension package to NPM now for it to get picked back up.

**Comment by sarvaje** [comment]
Yep, we need to publish the extension to NPM to get it back.

**Comment by hxlnt** [comment]
Cool--closing this out then.
