### ISSUE TITLE
Create integration test script

### ISSUE THREAD

**Issue by antross** [webhintio/webhint.io#810]
Currently CI runs webhint against the site, but doesn't verify a scan can actually be performed. We've had this result in bad builds being promoted to production in the past. Using something like puppeteer to actually drive the website in a more comprehensive integration test before the swap to production should help avoid repeating this problem in the future.

**Comment by molant** [comment]
We can probably create a script that uses puppeteer to open a browser, go to the staging website, navigate to different pages and verify we receive a 200 for all of them and finally performs a scan and a search.

We will be calling that script from the pipelines once it is done.

**Comment by LeoSL** [comment]
I will work on this

**Comment by molant** [comment]
Hi @LeoSL 

I'm sorry you are having issues with this one. We assumed some experience with puppeteer when we tagged it but you are right that could be a bit misleading.

The CI server we are using is Azure Pipelines. You can see the builds for all the webhint projects in [here](https://dev.azure.com/webhint/webhint/_build?definitionId=7).

The file that decides what is run in Azure DevOps is [azure-pipelines.yml](https://github.com/webhintio/webhint.io/blob/master/azure-pipelines.yml)

The staging environment is https://sonarwhal-staging.azurewebsites.net. It should look almost the same than the official website.

So this is what I'm thinking as a breakdown:

1. Add puppeteer to the project
1. Create `/helpers/integration-tests.js`. This is the script with the integration tests. This script should:
   * Start a [puppeteer](https://pptr.dev) instance
   * Navigate to the following URLs and verify the status code is 200 for each one of them:
     * https://sonarwhal-staging.azurewebsites.net
     * https://sonarwhal-staging.azurewebsites.net/search/?q=bla 
     * https://sonarwhal-staging.azurewebsites.net/scanner/
     * https://sonarwhal-staging.azurewebsites.net/about/changelog/1
     * https://sonarwhal-staging.azurewebsites.net/docs/user-guide/hints/

I've split this issue into 2 so the integration with Azure Pipelines is done at a different moment (#842).

Thanks for looking into this @LeoSL !

**Comment by molant** [comment]
Also re the gulp issues you are seeing I have no idea why. What version of node and in what platform are you working? Also, this should not be a blocker as you don't need to build the website to test https://sonarwhal-staging.azurewebsites.net

**Comment by LeoSL** [comment]
Thank you for the detailed explanation and quick reply @molant ! I really appreciate it!

I will work on that later today.
