### ISSUE TITLE
Add integration tests into the Azure Pipeline

### ISSUE THREAD

**Issue by molant** [webhintio/webhint.io#842]
#810 needs to be done first.

The work is modify [this line](https://github.com/webhintio/webhint.io/blob/214bffeadca179967e4093bf95b6b42570bcf03b/azure-pipelines.yml#L28) to call also the new script.
Something like `npm run test-staging && node helpers/integration-tests.js`

**Comment by uchemukolo** [comment]
I will like to work on this issue @molant

**Comment by molant** [comment]
Sure!

There's a PR for #810 (#843) so once that one lands feel free to submit a PR for this. Or if you don't want to wait, you can look into cherry-picking the change in #843 and create a new commit for this issue on top of it to see that everything works end-to-end.
We might have to do some gymnastics to rebase the final code once #843 gets merged (we've requested a couple changes) but we can help you with that if needed or we can take care of them before merging.

Does that sound like a good plan to you?
If you have any questions please don't hesitate to reach out to us!

**Comment by uchemukolo** [comment]
Sounds good!
I just cloned the repo and followed all the steps on the readme but when i run `npm start` i get the below attached error. Am i doing something wrong?

<img width="1080" alt="Screenshot 2019-10-08 at 10 31 37 PM" src="https://user-images.githubusercontent.com/30410066/66434915-818c8f80-ea1b-11e9-87b3-221dfe2f592d.png">

**Comment by molant** [comment]
Nope, that's fine. We have to update the docs 😓
If you navigate to `https://localhost:4000/server/` you should see something more colorful.

In any case, for this to work you actually don't need to build the website as you will be testing the staging environment (https://sonarwhal-staging.azurewebsites.net).

**Comment by molant** [comment]
@uchemukolo I'm working on improving the docs rights now. Look for a PR soon!

**Comment by molant** [comment]
Actually I just skipped the PR and push to master. If you get the latest version running `npm start` should work now as you expected. Also I've updated the `README.md`. There's still a bit more of work we want to do (see #360) but this should unblock most of the people running into the same issue as you.

**Comment by uchemukolo** [comment]
@molant I see that PR for #810 (#843) has been merged. I tried to pull the the latest changes locally using `git pull` but nothing was downloaded

**Comment by molant** [comment]
Are you working on a fork of this repo? In a different branch? There are a few reasons why this could happen.

Can you run `git branch -vv` and paste the output to have a bit more information?

Thanks!

**Comment by uchemukolo** [comment]
Yes I am working a a fork of the repo. Can I work directly from the original repo? @molant

**Comment by antross** [comment]
We typically recommend working on a fork, but it does change the git flow slightly. You'll need to fetch from upstream to get the latest commits then rebase them onto your fork's master branch.
```bash
git checkout master
git fetch upstream
git rebase upstream/master
```

**Comment by uchemukolo** [comment]
@antross i am getting access right error
<img width="1428" alt="Screenshot 2019-10-15 at 6 42 23 PM" src="https://user-images.githubusercontent.com/30410066/66855671-9c12bb80-ef7b-11e9-85a1-74c7acaf6b67.png">

**Comment by sarvaje** [comment]
@uchemukolo I think you need to configure the upstream remote repository.

`git remote add upstream https://github.com/webhintio/webhint.io.git`

**Comment by uchemukolo** [comment]
@sarvaje script to run integration tests has been added, but how do i test to know its working as expected?

**Comment by sarvaje** [comment]
I think you need to create a PR to run Azure pipeline

**Comment by molant** [comment]
Yes, please create a PR to this project so Azure can run it. We might need to tweak something on our side as the code will not be in the master branch but that's fine.

**Comment by uchemukolo** [comment]
I am still having issues getting the latest updates on the forked branch
i ran `git remote add upstream https://github.com/webhintio/webhint.io.git` 
`git fetch upstream`
still not able to get the latest updates from master.

when I cloned the repo directly i was getting `403` error when I tried to push
<img width="1428" alt="Screenshot 2019-10-15 at 9 49 53 PM" src="https://user-images.githubusercontent.com/30410066/66868742-d1c49e00-ef95-11e9-900b-c05295bea060.png">
cc: @molant @sarvaje

**Comment by molant** [comment]
Can you please run `git branch -vv` and paste the output?

**Comment by uchemukolo** [comment]
`git branch -vv`
<img width="1428" alt="Screenshot 2019-10-15 at 10 23 56 PM" src="https://user-images.githubusercontent.com/30410066/66870981-8b257280-ef9a-11e9-831a-ff2ad06af7b0.png">

**Comment by molant** [comment]
Not sure in what state you are because `git branch -vv` says you are in `master` of `upstream` but the previous one says you are in detached mode 🤔

If you are in the branch with the changes can you try doing `git push -u origin`? That should hopefully create a new branch in your fork and then you can do a PR from the github website.
