### ISSUE TITLE
Accessibility Issue reported as error for Webhint website

### ISSUE THREAD

**Issue by Shri-Humrudha** [webhintio/webhint.io#850]
Ran the tool against the webhint website, there is an accessibility issue reported.
Browser: Chrome
![Accessibility](https://user-images.githubusercontent.com/52764236/67126610-5557d800-f1ac-11e9-8b69-72f677fc868d.png)

**Comment by molant** [comment]
Yup, that's because some versions of Edge needed `none presentation` in order to work as expected with narrator 🙄

We can probably kill this fix now.

**Comment by molant** [comment]
@ststimac @dstory do you rember what version of Edge was this for?

**Comment by ststimac** [comment]
@molant I do not.

**Comment by molant** [comment]
We can probably remove this then. I believe it was fixed a long time ago.
