### ISSUE TITLE
Puppeteer integration tests during deployment are intermittently failing

### ISSUE THREAD

**Issue by utsavized** [webhintio/webhint.io#907]

**Comment by molant** [comment]
Could this be related to the server code not being ready?
I believe the node part of the site will not get started until there's a request to it, and it might take a few seconds to get it ready (and connection might be dropped?).

In another project what we ended up doing for testing before swapping was to just do requests until we get the page. I think we had a limit of 5 requests and we waited about 30 seconds in between 🤔

**Comment by utsavized** [comment]
> Could this be related to the server code not being ready?

This is what I suspected as well. I added a simple exponential back-off logic in the other [PR ](https://github.com/webhintio/webhint.io/pull/906) to see if a 5/10/15 second back-off between retries fixes the issue.
