### ISSUE TITLE
Remove GA from website

### ISSUE THREAD

**Issue by antross** [webhintio/webhint.io#925]
Triggered by questions in #913 and discussed at our sync last week, we want to remove Google Analytics from the website because:
1) Nobody is currently looking at the GA data
2) The data we do look at is gathered through webhint-specific code and stored in Application Insights
3) We want to only gather data we know we're going to use and can explicitly make anonymous to maximize user privacy

**Comment by molant** [comment]
Is there a plan to track click through from the tools to the documentation pages?

**Comment by antross** [comment]
> Is there a plan to track click through from the tools to the documentation pages?

Yes for browser integrations we're working on. We don't currently have work tracking this from the other entry points (e.g. the browser extension) but I suspect that would be useful as well. We'd just need to update the extension to append a source param and we could follow that through. Or did I misunderstand your question?

**Comment by molant** [comment]
> We'd just need to update the extension to append a source param and we could follow that through.

My question was more about what is going to record how many visits come with that param. If the plan is to report it via AppInsights that's fine.
Another problem is the data retention, especially if at one moment there are OKRs about any of these values (although we already have that problem).

**Comment by antross** [comment]
> My question was more about what is going to record how many visits come with that param. If the plan is to report it via AppInsights that's fine.

@molant, yes the plan is to report it via App Insights (and was implemented here https://github.com/webhintio/webhint.io/pull/913)
