### ISSUE TITLE
Nellie's working overtime... all the time?

### ISSUE THREAD

**Issue by sarvaje** [webhintio/webhint.io#955]
This screen is showing very often now (or always) so we need to take a look.

The workaround is copy the permalink and pasting in the address bar.

**Comment by sarvaje** [comment]
Fixed, there was some "dead messages" in the queue that was triggering this screen to appear.

I requeue the jobs and now it should be clean.

There are two "dead messages"  still in the results queue that are constantly failing, I don't know exactly why.

@antross do you think we should open an issue to investigate why those messages are failing?

**Comment by antross** [comment]
> do you think we should open an issue to investigate why those messages are failing?

Probably. Can we also clean them out and see if they reoccur?
