### ISSUE TITLE
https://webhint.io/scanner/ fails to scan

### ISSUE THREAD

**Issue by JZebra** [webhintio/webhint.io#971]
Bug report:

https://webhint.io/scanner/ fails to scan.
MacOS version 10.15.7
Google Chrome Version 91.0.4472.77

Repro steps: 
- Go to https://webhint.io/scanner/
- enter 'http://www.google.com'
- I am directed to an error page:

![Screen Shot 2021-06-09 at 6 08 15 PM](https://user-images.githubusercontent.com/5651471/121449149-14e33a00-c94e-11eb-937c-8c2647af7c44.png)

**Comment by sarvaje** [comment]
@JZebra thanks for the report. The service should work normally now.

Please feel free to open it again if it happens again.
